### PR TITLE
Create pulse funcition

### PR DESCRIPTION
**Pull request by gfth4x07**
Just a function to pulse a pin. This function will take easy the serial communication and write in a Shift-Register.
I tested in a Raspberry Pi 2 B and it's works.

### CODE REVIEW

**Comment by gfth4x07** [comment]
Now Pingo supports GrovePI Board.
I have tested!

**Comment by Vido** [comment]
@gfth4x07, thanks for your time.

Please, fix the flake8 warnings.

```
0.45s$ flake8 --ignore=E501 pingo
pingo/rpi/__init__.py:4:34: W292 no newline at end of file
pingo/rpi/grove.py:11:13: F401 'grovepi' imported but unused
pingo/rpi/grove.py:54:67: E226 missing whitespace around arithmetic operator
pingo/rpi/grove.py:66:52: E226 missing whitespace around arithmetic operator
```

I will point them in the comments...

**Comment by gfth4x07** [comment]
I think it's better import grovepi as grovepi. The libraries name is grovepi why not use this name?

**Comment by Vido** [comment]
@gfth4x07 ok...
galileo.py does it the same way...

Just add a dirty fix:
```python
import grovepi as grovepi  # noqa
```

**Comment by Vido** [comment]
Thanks to @gfth4x07, now Pingo has GrovePi.

**Pull request merged**
